indent_style = "Block"
use_small_heuristics = "Max"
binop_separator = "Front"
combine_control_expr = false
control_brace_style = "AlwaysSameLine"
fn_args_layout = "Compressed"
brace_style = "SameLineWhere"
empty_item_single_line = true
fn_single_line = true
where_single_line = false
format_macro_matchers = false
format_macro_bodies = true
hard_tabs = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = false
max_width = 100
merge_derives = true
force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = true
struct_lit_single_line = true
trailing_comma = "Never"
trailing_semicolon = false
type_punctuation_density = "Wide"
use_field_init_shorthand = true
format_code_in_doc_comments = true
match_arm_blocks = true
overflow_delimited_expr = false
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
edition = "2018"
normalize_doc_attributes = true