binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
brace_style = "SameLineWhere"
combine_control_expr = false
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_args_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = false
format_macro_matchers = false
format_macro_bodies = true
format_strings = false
hard_tabs = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_block_trailing_comma = false
max_width = 100
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
report_fixme = "Never"
report_todo = "Never"
space_after_colon = true
spaces_around_ranges = true
struct_field_align_threshold = 0
struct_lit_single_line = true
trailing_comma = "Never"
trailing_semicolon = false
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = false
wrap_comments = false